version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "ispbackup"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ispbackup"

  minio:
    image: minio/minio:latest
    ports:
      - "9002:9000"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
  
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc alias set myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/backups-bucket --ignore-existing;
      /usr/bin/mc anonymous set public myminio/backups-bucket;
      exit 0;
      "
